[project]
name = "cursor-mcp-server"
version = "0.1.0"
description = "A basic MCP server for Cursor"
requires-python = ">=3.10"
dependencies = [
    "mcp",
]

[project.scripts]
cursor-mcp-server = "mcp_server:main"
